### ISSUE TITLE
CTRL+enter bypassa lo stato del cloud upload

### ISSUE THREAD

**Issue by nitaku** [nitaku/webvis_lab#12]
Se si preme CTRL+enter subito dopo aver fatto delle modifiche, run viene eseguito subito, mentre invece deve attendere che il cloud upload sia terminato. In questo caso, il countdown di tre secondi può essere ignorato, perchè l'utente ha richiesto l'esecuzione del codice e quindi è sicuro che possiamo salvare subito.

**Comment by andreaderrico2** [comment]
Ok, risolto, passo e ...chiudo
