### ISSUE TITLE
Tab non corrispondente all'editor

### ISSUE THREAD

**Issue by nitaku** [nitaku/webvis_lab#16]
A volte un tab è selezionato, ma è aperto un editor diverso (ad esempio alla creazione di un nuovo file). Forse è meglio raggruppare la selezione del tab e l'apertura dell'editor in un'unica funzione, e poi chiamare sempre quella (@andreaderrico2 somiglia la discorso che facevi sul fare il codice a oggetti).

**Comment by andreaderrico2** [comment]
Alla creazione del file il problema è risolto c'era un errore nel codice...
Se ci sono altri esempi ditemeli intanto chiudo la issue.. :-)
