### ISSUE TITLE
Togliere autoplay

### ISSUE THREAD

**Issue by nitaku** [nitaku/webvis_lab#2]
Il run automatico all'apertura è meglio disattivarlo, perchè un codice contenente un errore potrebbe impedire l'accesso all'editor. Basta fare un codice che fa un ciclo pesante che crasha la scheda, a quel punto l'unico modo è mettere a posto i file da WinSCP & co.

Al posto dell'output a quel punto ci può stare una scritta che dice "Press run to execute the code." o simile.

**Comment by andreaderrico2** [comment]
Fatto!
