### ISSUE TITLE
Mostrare simboli spazi e tab

### ISSUE THREAD

**Issue by nitaku** [nitaku/webvis_lab#20]
Soprattutto per i linguaggi con l'indentazione semantica come coffeescript, è meglio vedere i tab e gli spazi rappresentati come simboli diversi (credo che codemirror lo supporti). Altrimenti c'è il rischio di introdurre un errore di sintassi invisibile.

**Comment by andreaderrico2** [comment]
Risolto... Passo ... e chiudo...!

**Comment by andreaderrico2** [comment]
Risolto... Passo ... e chiudo...!
