### ISSUE TITLE
Blocco chiusura scheda

### ISSUE THREAD

**Issue by nitaku** [nitaku/webvis_lab#21]
Se per sbaglio chiudi la scheda e poi la riapri rischi di perdere tutto il lavoro, perchè a quanto pare il codice che viene caricato è stravecchio (forse perchè il browser riempie le textarea degli editor con i valori che si ricorda? boh). Poi se non te ne accorgi subito ci salvi sopra (come ho appena fatto :D) e perdi tutto.
Non so se ci sono soluzioni migliori, ma forse non sarebbe male uno di quegli avvisi noiosi che ti chiede se sei sicuro di chiudere la scheda.

**Comment by andreaderrico2** [comment]
Messo l'avviso... Chiudo...
