### ISSUE TITLE
Menù per roba varia

### ISSUE THREAD

**Issue by nitaku** [nitaku/webvis_lab#3]
Forse si può mettere un menù per roba varia (alla Chrome con tre lineette) dove ad esempio può stare la chiamata che mostra un popup con le scorciatoie da tastiera. Il tasto che apre il menù potrebbe stare a destra nella barra delle schede (opposto alla cartellina).

**Comment by nitaku** [comment]
Potrebbe contenere anche i comandi stessi presentati nelle scorciatoie (find, ma anche ingrandisci e rimpicciolisci caratteri)... forse in questo caso il popup che descrive le scorciatoie diventa meno utile.

**Comment by nitaku** [comment]
Nel menù si può mettere anche un "Download all as ZIP" che scarica tutto il codice zippato.

**Comment by andreaderrico2** [comment]
Avevo creato una issue per inserire "Download all as ZIP" e l'ho inserito nel menu folder... Ho chiuso quella issue...

**Comment by fabiovalse** [comment]
Nel menù nuovo che hai creato io metterei le linee di separazione tra le varie voci in un colore chiaro, non nero.

**Comment by andreaderrico2** [comment]
Fatto il menù e inserite alcune voci (che aumenteranno)... Chiudo questa issue per ora... Probabilmente verrà riaperta con altre aggiunte da fare...
