### ISSUE TITLE
Template, syntax highlighting e linter (?) per PHP

### ISSUE THREAD

**Issue by nitaku** [nitaku/webvis_lab#31]
Quando si crea index.php, dovrebbe esserci un template adeguato (se si fa la lista dei template all'apertura di un nuovo gist, uno di questi template sarà "PHP").
Oltre a questo, index.php fa parte del trio di file standard da aprire (è praticamente al posto di index.html).
PHP ha anche bisogno del syntax highlighting, e se esiste di un linter.

**Comment by andreaderrico2** [comment]
Inserito il syntax highlighting per PHP e adesso se c'è un php dovrebbe essere visualizzato e "checked" al caricamento...

Lascio aperta la issue per template e linter? Forse è meglio fare due uniche issue una per i template da inserire e una per i linter (qualora esistano)?

**Comment by nitaku** [comment]
Sì, tieni le issue separate come dicevi. Chiudo qui.

**Comment by nitaku** [comment]
Però a me il PHP lo highlighta come HTML.... :(

**Comment by andreaderrico2** [comment]
Ah si, ci sta, ho messo la modalità che era descritta come php+html :-) deve essere quello...

----- Messaggio originale -----
Da: "Matteo Abrate" <notifications@github.com>
Inviato: ‎13/‎07/‎2015 19:50
A: "nitaku/webvis_lab" <webvis_lab@noreply.github.com>
Cc: "andreaderrico2" <andreaderrico2@gmail.com>
Oggetto: Re: [webvis_lab] Template, syntax highlighting e linter (?) per PHP(#31)

Però a me il PHP lo highlighta come HTML.... :(

**Comment by nitaku** [comment]
Boh, php+html sembrerebbe giusta, è che CodeMirror fa uno schifo, vedi qui: http://wafi.iit.cnr.it/webvis_tmp/lab/editor/interface?gist_id=0e36dcc66487cd0997c1

**Comment by andreaderrico2** [comment]
Quindi cosa consigli di fare? Metto solo php?

**Comment by nitaku** [comment]
Non lo so, vedi quale ti sembra funzioni meglio... Ora a me mi fa l'highlight solo della parte HTML (e rincretinisce quando comincia il JS).

**Comment by andreaderrico2** [comment]
Ok... messo a posto, mancava il C-like mode che aiuta all'highlighting dei vari linguaggi...

**Comment by nitaku** [comment]
Perfetto, funziona benissimo.

**Comment by andreaderrico2** [comment]
Yuppi… 😊






Inviata da Windows Mail





Da: Matteo Abrate
Data invio: ‎martedì‎ ‎14‎ ‎luglio‎ ‎2015 ‎09‎:‎56
A: nitaku/webvis_lab
Cc: Andrea D'Errico





Perfetto, funziona benissimo.
