### ISSUE TITLE
Syntax highlighting per .py e .R

### ISSUE THREAD

**Issue by nitaku** [nitaku/webvis_lab#32]
Aggiungere syntax highlighting per codice python (.py) e R (.R maiuscola). Se ci sono, anche dei linter.

**Comment by andreaderrico2** [comment]
Ma avevi visto che non funzionavano? Perchè il syntax highlighting per python lo avevo già messo, quello per R l'ho messo ora... I linter, mmm... :-)

**Comment by nitaku** [comment]
Python l'ho riprovato e ora funziona... forse boh, non l'ha attivato quando ho creato il file nuovo? R non mi funziona ancora (occhio all'estensione .R che è maiuscola).

**Comment by andreaderrico2** [comment]
Ok... ora funziona anche il mode "R"

**Comment by nitaku** [comment]
Yay!
