### ISSUE TITLE
Popup per rinominare i file

### ISSUE THREAD

**Issue by fabiovalse** [nitaku/webvis_lab#8]
Per rinominare i file, dopo il click sulla matita, al posto di un popup, si potrebbe rendere il contenitore della label del file a fianco editabile e quindi spostarci il cursore. Rinominare il nome poi si farebbe direttamente da lì senza popup.

**Comment by fabiovalse** [comment]
Si potrebbe addirittura togliere la matita e sul doppio click sulla label di un file rendere editabile la label.

A questo punto cambierei il cestino con una semplice X.

**Comment by fabiovalse** [comment]
Di conseguenza l'add file dovrebbe essere conforme con queste modifiche e quindi aggiungere una riga con il cursore pronto per inserire il nome del file etc...

**Comment by nitaku** [comment]
Il click sul nome del file dovrebbe mostrare il suo tab, aprire l'editor su quel tab e chiudere il menu. Però la funzione rinomina potrebbe momentaneamente disattivare questo comportamento e rendere il nome del file editabile, per poi tornare a funzionare così una volta fatto.

**Comment by andreaderrico2** [comment]
Al momento ho fatto così: sul click della matita l'input si trasforma in type text inserendo un nome e pigiando invio parte la procedura di rinomina... Può andare?

**Comment by nitaku** [comment]
Sembra di sì (ovviamente senza alert! :D )

**Comment by nitaku** [comment]
Il click sul nome del file crea problemi se il file non era visibile (mostra il suo editor, ma non mostra il suo tab!).

**Comment by andreaderrico2** [comment]
Quale alert non vuoi?? Tutti?

Il giorno 2 luglio 2015 18:02, Matteo Abrate <notifications@github.com> ha
scritto:

**Comment by andreaderrico2** [comment]
Ok.. quello che dice Matteo lo metto a posto successivamente appena
riesco...


Il giorno 2 luglio 2015 18:03, Andrea D'Errico <andreaderrico2@gmail.com>
ha scritto:

**Comment by nitaku** [comment]
Io ho visto l'alert del rinomina. Gli altri ora non so.

**Comment by andreaderrico2** [comment]
Dovrei aver fatto tutto compreso risolvere il problema che diceva Matteo: "Il click sul nome del file crea problemi se il file non era visibile (mostra il suo editor, ma non mostra il suo tab!)."

Chiudo.. in caso riapritela...
