### ISSUE TITLE
Menù cartella e tab

### ISSUE THREAD

**Issue by fabiovalse** [nitaku/webvis_lab#9]
Se si apre il menù cliccando sulla cartella, lo si lascia aperto e si clicca sui tab il menù dovrebbe chiudersi?
- Sì: problema risolto;
- No: il tab finisce leggermente sopra il menù della cartella.

**Comment by andreaderrico2** [comment]
Ora se il menù files è aperto e si clicca su un tab si apre il tab e si chiude il menu files... Passo e ...chiudo
